name: Pull Request Deployment
on: pull_request
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test application
        run: |
          docker build --tag=coco-cat:test .
          docker run coco-cat:test npm run test
  deploy:
    name: OpenShift Deployment
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Pipeline Action
        uses: bcgov/openshift-launchpad-deployment@master
        with:
          MODE: client
          BRANCH: "${{ github.event.pull_request.head.ref }}"
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN_TEST }}
          NAMESPACE: apdwlc-test
          APP_NAME: catalogue-pr${{ github.event.number }}
          API_URL: https://test.com
          CLIENT_PORT: 3000
